#ifndef _COMPILED_GLSL_
#define _COMPILED_GLSL_
#define _EnvCol
#define _LDR
#define _Sun
#define _CToneFilmic
const float PI = 3.1415926535;
const float PI2 = PI * 2.0;
const vec2 shadowmapSize = vec2(0, 0);
const float shadowmapCubePcfSize = 0.001;
const int shadowmapCascades = 1;
const float ssrRayStep = 0.04;
const float ssrMinRayStep = 0.05;
const float ssrSearchDist = 5.0;
const float ssrFalloffExp = 5.0;
const float ssrJitter = 0.6;
const int skinMaxBones = 8;

#endif // _COMPILED_GLSL_
